### ISSUE TITLE
Replace parted calls by libparted

### ISSUE THREAD

**Issue by phatina** [storaged-project/storaged#44]
This dependency is not logical from layerining point of view. Libparted should provide th same functionality.

**Comment by andreas-fatal** [comment]
There's also sfdisk, sgdisk, .... calls. Hopefully all of these could be replaced with a single implementation rather than requiring util-linux, sgdisk, parted, etc. I'm not really familiar with (lib)parted, but I think atleast libfdisk (now used by sfdisk, et.al. in util-linux) should cover all the cases.

**Comment by phatina** [comment]
> There's also sfdisk, sgdisk, .... calls. Hopefully all of these could be replaced with a single implementation rather than requiring util-linux, sgdisk, parted, etc. I'm not really familiar with (lib)parted, but I think atleast libfdisk (now used by sfdisk, et.al. in util-linux) should cover all the cases.

@vpodzime, are we able to introduce the necessary API into libblockdev?

**Comment by vpodzime** [comment]
> @vpodzime, are we able to introduce the necessary API into libblockdev?

Hard to say from a list of tools you are using. :) But if you can use it, *libblockdev* can use it in the same way replacing what's possible with library calls.

**Comment by tsmetana** [comment]
Was this one not fixed with commit 102d786 already?

**Comment by vpodzime** [comment]
> Was this one not fixed with commit 102d786 already?

It was.
